### ISSUE TITLE
tried to use... immediate error

### ISSUE THREAD

**Issue by securas** [MennoMax/gift#1]
using godot 3.1.2 the script connects only to error after the first message is typed:

![image](https://user-images.githubusercontent.com/2881755/77847945-bc69c600-71fb-11ea-9fe7-4bc91cd82a77.png)

**Comment by MennoMax** [comment]
Thank you for reporting this. I tested it with 3.2 and had no issues there, so I am currently downloading 3.1.2.

**Comment by MennoMax** [comment]
I can't seem to reproduce this error with 3.1.2 or 3.2 - messages are being received and sent properly. Could you show me your code?

**Comment by securas** [comment]
I've not tested your fix yet but thanks!
