### ISSUE TITLE
Send commands as whisper

### ISSUE THREAD

**Issue by MrEliptik** [MennoMax/gift#10]
Hey, I'm using your addon to create interactive overlays with Godot, and first of all I want to thank you for your work! 

I would the viewers to be able to send commands but as whisper instead of a chat message. This would allow the chat to not be flooded with commands, especially when making high interactivity overlays. 

Have you thought about that? If you want some help, I could look into it, and make a PR once I have something working.

Regards,
Victor

**Comment by MennoMax** [comment]
This is already possible, the add_command function has a 'where' parameter that you can just pass a WhereFlag.WHISPER to register a command to be executed from whispers.

**Comment by MrEliptik** [comment]
Oh sorry, I missed it! Thanks for your response, I'll try it tomorrow.
