### ISSUE TITLE
Chat_message Signal only returns the first word?

### ISSUE THREAD

**Issue by R3m3mb3rM3** [MennoMax/gift#6]
I might be dumb but is that on purpose or did I do something wrong?

I connected the chat_message signal, I have the message as a "String" argument and when I print it its only the first word.

**Comment by danreeves** [comment]
I'm also seeing this. Did you resolve the issue @R3m3mb3rM3

**Comment by danreeves** [comment]
I tracked it down to this line: https://github.com/MennoMax/gift/blob/master/addons/gift/gift_node.gd#L188

```diff
-var msg : PoolStringArray = message.split(" ", true, 4)
+var msg : PoolStringArray = message.split(" ", true, 3)
```

**Comment by MennoMax** [comment]
Yes, it should however work as intended, might be a bug of Godot.

Despite `maxsplit`, the resulting array has a length of 5.

**Comment by danreeves** [comment]
Thanks!
