### ISSUE TITLE
Comands with arguments are not working

### ISSUE THREAD

**Issue by Rumidom** [MennoMax/gift#8]
on function handle_message, message.split maxsplit should be 4 not 3:
`var msg : PoolStringArray = message.split(" ", true, 4)`

otherwise msg[3] will not be reconized as a comand, and msg[4] wont exist.

**Comment by MennoMax** [comment]
Thanks, missed this while fixing #6!

Closed by 4ecb6331529018c85adb8246e90d09fd50037dc6.
